//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string Remarks { get; set; }
        public string DeskPhone { get; set; }
        public string CellPhone { get; set; }
        public string HomePhone { get; set; }
        public bool HasIMAccount { get; set; }
        public string IMAccount { get; set; }
        public bool IsPager { get; set; }
        public bool PersonalCell { get; set; }
        public string Notes { get; set; }
        public string Email { get; set; }
        public bool ShowOnBoard { get; set; }
        public string Division { get; set; }
    
        public virtual EmployeeStatu EmployeeStatu { get; set; }
    }
}
